# Generated by Django 4.2.6 on 2024-03-14 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0089_ordernotification_seller_prod_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_aquascape',
            fields=[
                ('aqsp_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_image', models.ImageField(blank=True, null=True, upload_to='aqsp_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
