# Generated by Django 4.2.6 on 2024-03-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0091_rename_sub_image_add_aquascape_aqsp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='not_available', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.CharField(blank=True, default='hi', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.CharField(blank=True, default='hi', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vechicle_type',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
