# Generated by Django 4.2.6 on 2024-03-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0092_userprofile_availability_userprofile_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='status',
            new_name='delboy_status',
        ),
    ]
