# Generated by Django 4.2.6 on 2024-03-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0093_rename_status_userprofile_delboy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='delboy_status',
            field=models.CharField(choices=[('Nil', 'Nil'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='Nil', max_length=10),
        ),
    ]
