# Generated by Django 4.2.6 on 2024-03-19 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0097_assigneddeliveryagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragentdistance',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_distances', to=settings.AUTH_USER_MODEL),
        ),
    ]
