# Generated by Django 4.2.6 on 2024-03-19 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0098_alter_useragentdistance_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigneddeliveryagent',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
