# Generated by Django 4.2.6 on 2024-03-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0099_assigneddeliveryagent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigneddeliveryagent',
            name='status',
            field=models.CharField(choices=[('OR', 'Order Requested'), ('PI', 'PICKED'), ('AP', 'AT_POINT'), ('SU', 'Successful')], default='OR', max_length=2),
        ),
    ]
