# Generated by Django 4.2.6 on 2024-03-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0100_assigneddeliveryagent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigneddeliveryagent',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assigneddeliveryagent',
            name='ready_for_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
