# Generated by Django 4.2.6 on 2024-03-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0101_assigneddeliveryagent_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigneddeliveryagent',
            name='otp',
            field=models.CharField(default=123456, max_length=6),
            preserve_default=False,
        ),
    ]
