# Generated by Django 4.2.6 on 2024-03-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0102_assigneddeliveryagent_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigneddeliveryagent',
            name='otp',
            field=models.CharField(default='123456', max_length=6),
        ),
    ]
