# Generated by Django 4.2.6 on 2024-03-21 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0103_alter_assigneddeliveryagent_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigneddeliveryagent',
            name='delivery_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
