# Generated by Django 4.2.6 on 2024-03-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0104_assigneddeliveryagent_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigneddeliveryagent',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='assigneddeliveryagent',
            name='delivery_date_alloted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
