# Generated by Django 4.2.6 on 2024-03-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0105_remove_assigneddeliveryagent_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='mobile_number',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
