# Generated by Django 4.2.6 on 2024-03-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0107_alter_useraddress_city_alter_useraddress_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
