# Generated by Django 4.2.6 on 2024-04-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0110_product_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
